import { chromium } from 'playwright';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import express from 'express';
import mongoose from 'mongoose';
import jwt from 'jsonwebtoken';
import assert from 'node:assert/strict';
process.env.JWT_SECRET='browser-isolated-test-secret';process.env.LLM_PROVIDER='local';delete process.env.GEMINI_API_KEY;delete process.env.LLM_API_KEY;
const {apiRouter}=await import('../backend/routes');const {User,Product,Lead}=await import('../backend/models');
const mongo=await MongoMemoryReplSet.create({replSet:{count:1}});await mongoose.connect(mongo.getUri());
const users:any={};for(const [role,phone]of [['manager','1111111111'],['customer','2222222222'],['admin','3333333333']] as const){const user=await User.create({name:`Test ${role}`,phone,password:'hash',role,status:'approved',storeName:'Test Store',location:'Test Village'});users[role]={user:{_id:String(user._id),name:user.name,role:user.role,storeName:user.storeName},token:jwt.sign({id:user._id,role},process.env.JWT_SECRET!)};}
await Product.create({name:'Rice',description:'Local fresh rice',category:'Groceries',price:200,actualPrice:200,quantity:10,managerId:users.manager.user._id,storeDetails:{storeName:'Test Store',location:'Test Village',contactNumber:'1111111111'}});
const app=express();app.use(express.json({limit:'4mb'}));app.use('/api',apiRouter);const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const api=`http://127.0.0.1:${(server.address() as any).port}`;
const browser=await chromium.launch({headless:true}),page=await browser.newPage();const errors:string[]=[];let healthChecks=0,fallbackLanguage=false,failSpeech=false,failSynthesis=false;const spoken:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',message=>{if(message.type()==='log')console.log('Browser:',message.text());});
await page.route('**/api/**',async route=>{
  const url=new URL(route.request().url());
  if(url.pathname==='/api/ai/translate'){const body=route.request().postDataJSON();return route.fulfill({json:{translatedText:body.text}});}
  if(url.pathname==='/api/ai/speech/status'){healthChecks++;return route.fulfill({status:healthChecks===1?503:200,json:{state:healthChecks===1?'error':'ready',model:'local'}});}
  if(url.pathname==='/api/ai/speak'){if(failSynthesis)return route.fulfill({status:503,json:{message:'Could not play spoken reply. Tap replay to try again.'}});spoken.push(route.request().postDataJSON().language);return route.fulfill({contentType:'audio/wav',body:Buffer.from('RIFFstubWAVE')});}
  if(url.pathname==='/api/ai/transcribe-and-intent'){if(failSpeech)return route.fulfill({status:503,json:{message:'Speech service unavailable. You can type your command.'}});fallbackLanguage=route.request().postDataBuffer()!.toString().includes('bn');return route.fulfill({json:{transcript:'চাল খুঁজুন',language:'bn'}});}
  const response=await route.fetch({url:api+url.pathname+url.search});return route.fulfill({response});
});
await page.addInitScript(({user,token})=>{
  (window as any).__name=new Function('value','return value');
  if(!localStorage.getItem('user')){localStorage.setItem('user',JSON.stringify(user));localStorage.setItem('token',token);}
  class FakeRecognition{
    lang:any;onerror:any;onend:any;onresult:any;
    start(){(window as any).__recognitionLocale=this.lang;if((window as any).__failRecognition){setTimeout(()=>{this.onerror?.({error:'network'});this.onend?.();},10);return;}setTimeout(()=>{const transcript=(window as any).__voiceTurns?.shift()||'চাল খুঁজুন';const final:any=[{transcript,confidence:(window as any).__confidence??0.95}];final.isFinal=true;this.onresult?.({resultIndex:0,results:[final]});this.onend?.();},20);}stop(){this.onend?.();}abort(){}
  }
  (window as any).SpeechRecognition=FakeRecognition;
  Object.defineProperty(window,'speechSynthesis',{value:{getVoices:()=>[],cancel(){},speak(){}}});
  Object.defineProperty(navigator,'mediaDevices',{value:{getUserMedia:async()=>{if((window as any).__denyMic)throw new DOMException('Denied','NotAllowedError');return {getTracks:()=>[{stop(){}}]};}}});
  (window as any).AudioContext=class {sampleRate=16000;destination={};async resume(){}async close(){}createMediaStreamSource(){return{connect(){},disconnect(){}};}async decodeAudioData(){return{};}createBufferSource(){return {connect(){},onended:null,start(){setTimeout(()=>this.onended?.(),50);},stop(){}};}createGain(){return{gain:{value:0},connect(){},disconnect(){}};}createScriptProcessor(){const processor={connect(){},disconnect(){},onaudioprocess:null};setTimeout(()=>processor.onaudioprocess?.({inputBuffer:{getChannelData:()=>new Float32Array([0.1,0.2,0.1])}}),10);return processor;}};
},users.manager);
await page.emulateMedia({reducedMotion:'reduce'});
const origin=process.env.BROWSER_TEST_ORIGIN||'http://127.0.0.1:5178';
async function role(name:string){await page.evaluate(({user,token})=>{localStorage.setItem('user',JSON.stringify(user));localStorage.setItem('token',token);},users[name]);}
async function send(text:string){await page.locator('.agent-composer input').fill(text);await page.locator('.agent-send').click();await page.waitForFunction(()=>!document.querySelector('.agent-send .animate-spin'));}
try{
  await page.goto(origin);await page.getByRole('heading',{name:/Local finds/}).waitFor();
  await page.waitForTimeout(700);await page.screenshot({path:'tests/artifacts/home-desktop.png',fullPage:true});
  for(const lang of ['hi','bn','ta','te','mr','gu']){
    await page.getByTestId('site-language').selectOption(lang);await page.goto(origin+'/marketplace');await page.locator('[data-product-id]').waitFor();const text=await page.locator('main').innerText();assert.ok(!text.includes('All Categories'));assert.ok(!text.includes('Newest first'));assert.ok(!text.includes('Clear filters'));
    await role('manager');await page.goto(origin+'/manager');await page.waitForFunction(()=>document.body.innerText.includes('Test Store'));assert.ok(!(await page.locator('main').innerText()).includes('My Inventory'));
    await role('admin');await page.goto(origin+'/admin');await page.locator('main h1').waitFor();assert.ok(!(await page.locator('main').innerText()).includes('Customer Access Management'));
    await role('customer');await page.goto(origin+'/customer?tab=requests');await page.locator('main h1').waitFor();assert.ok(!(await page.locator('main').innerText()).includes('No requests yet'));
  }
  await role('manager');await page.goto(origin+'/manager');await page.getByTestId('site-language').selectOption('bn');
  await page.locator('.agent-launcher').click();await page.waitForURL('**/marketplace?search=*');assert.equal(await page.evaluate(()=>(window as any).__recognitionLocale),'bn-IN');assert.equal(new URL(page.url()).searchParams.get('search'),'চাল');
  await page.waitForFunction(()=>!document.body.innerText.includes('স্থানীয় কণ্ঠ ইঞ্জিন নেই।'));assert.ok(healthChecks>=2);await page.screenshot({path:'tests/artifacts/assistant-bengali.png'});
  await page.locator('.agent-autosave input').uncheck();const before=await Product.countDocuments();await send('মধু যোগ করুন ২০০ টাকা');await page.locator('.agent-draft .button-primary').waitFor();assert.equal(await Product.countDocuments(),before);await page.locator('.agent-draft .button-primary').click();await page.waitForURL('**/manager');assert.equal(await Product.countDocuments(),before+1);
  await page.locator('.agent-autosave input').check();await send('চাল যোগ করুন দুইশো টাকা');await page.waitForFunction(()=>document.querySelector('.chat-message.assistant:last-of-type')?.textContent?.includes('পণ্য সংরক্ষণ'));assert.equal(await Product.countDocuments(),before+2);
  await page.evaluate(()=>{(window as any).__voiceTurns=['নতুন পণ্য','চাল','দুইশো টাকা'];});await page.locator('.agent-composer button[type="button"]').click();await page.waitForFunction(()=>document.querySelectorAll('.chat-message.assistant').length>=7);await page.waitForTimeout(500);assert.equal(await Product.countDocuments(),before+3,'Multi-turn voice must ask, listen and create once');
  await page.evaluate(()=>{(window as any).__voiceTurns=['চাল যোগ করুন দুইশো টাকা'];(window as any).__confidence=0.4;});await page.locator('.agent-composer button[type="button"]').click();await page.locator('.agent-draft .button-primary').waitFor();assert.equal(await Product.countDocuments(),before+3);await page.locator('.agent-draft .button-secondary').click();
  await page.evaluate(()=>{(window as any).__confidence=0.95;});await page.locator('.agent-footer button').click();await page.waitForTimeout(60);await page.locator('.agent-composer button[type="button"]').click();await page.waitForURL('**/marketplace?search=*');assert.equal(fallbackLanguage,true);assert.ok(spoken.includes('bn'));
  await page.evaluate(()=>{(window as any).__failRecognition=true;});await page.locator('.agent-composer button[type="button"]').click();await page.waitForTimeout(100);await page.locator('.agent-composer button[type="button"]').click();await page.waitForTimeout(400);assert.equal(await page.locator('.agent-error').count(),0);
  await page.evaluate(()=>{(window as any).__failRecognition=false;delete (window as any).SpeechRecognition;});await page.locator('.agent-composer button[type="button"]').click();await page.waitForTimeout(60);await page.locator('.agent-composer button[type="button"]').click();await page.waitForTimeout(400);assert.equal(await page.locator('.agent-error').count(),0);
  failSpeech=true;await page.locator('.agent-composer button[type="button"]').click();await page.waitForTimeout(60);await page.locator('.agent-composer button[type="button"]').click();await page.locator('.agent-error').waitFor();failSpeech=false;await send('hello');await page.locator('.agent-error').waitFor({state:'hidden'});
  failSynthesis=true;await send('hello');await page.locator('.agent-error').waitFor();failSynthesis=false;await page.locator('.agent-toolbar button').nth(1).click();await page.locator('.agent-error').waitFor({state:'hidden'});
  await send('Remember that I prefer Bengali');assert.equal(JSON.parse(await page.evaluate(()=>localStorage.getItem('aarohan-agent-preferences')!)).state.language,'bn');await send('Forget that I prefer Bengali');assert.equal(JSON.parse(await page.evaluate(()=>localStorage.getItem('aarohan-agent-preferences')!)).state.language,undefined);
  await page.evaluate(()=>{(window as any).__denyMic=true;});await page.locator('.agent-composer button[type="button"]').click();await page.locator('.agent-error').waitFor();assert.ok((await page.locator('.agent-error').innerText()).length>0);await send('open marketplace');
  await page.locator('.agent-header button').click();
  await page.getByTestId('site-language').selectOption('en');await page.goto(origin+'/marketplace');await page.locator('[data-product-id]').first().focus();await page.keyboard.press('Enter');await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
  // Voice must use the actual open dialog instead of an older search's first item.
  const honey=await Product.findOne({name:'মধু'});assert.ok(honey);
  await role('customer');await page.goto(origin+`/marketplace?product=${honey._id}`);await page.getByTestId('site-language').selectOption('bn');await page.getByRole('dialog').waitFor();
  await page.evaluate(()=>{(window as any).__denyMic=false;(window as any).SpeechRecognition=class {lang:any;onresult:any;onend:any;start(){setTimeout(()=>{const result:any=[{transcript:(window as any).__voiceTurns.shift(),confidence:0.95}];result.isFinal=true;this.onresult?.({resultIndex:0,results:[result]});this.onend?.();},20);}stop(){this.onend?.();}abort(){}};(window as any).__voiceTurns=['এটা অর্ডার করো','হ্যাঁ করুন'];window.dispatchEvent(new Event('agent-open'));});
  await page.locator('.agent-composer button[type="button"]').click();await page.waitForURL('**/customer?tab=requests');assert.ok(await Lead.exists({customer:users.customer.user._id,product:honey._id}),'Spoken order plus spoken yes must create the actual selected product inquiry');
  await role('manager');await page.goto(origin+'/account');await page.getByTestId('site-language').selectOption('en');
  await page.goto(origin+'/account');await page.getByLabel('Full Name',{exact:true}).fill('Updated manager');await page.getByRole('button',{name:'Save Changes',exact:true}).click();await page.getByRole('button',{name:'Confirm',exact:true}).click();await page.getByText('Account updated.',{exact:true}).waitFor();assert.equal((await User.findById(users.manager.user._id))!.name,'Updated manager');
  for(const width of [320,375,768,1440]){await page.setViewportSize({width,height:900});await page.goto(origin);assert.ok(await page.evaluate(()=>{if(document.documentElement.scrollWidth>window.innerWidth)console.log([...document.querySelectorAll('*')].filter(e=>e.getBoundingClientRect().right>window.innerWidth).map(e=>({tag:e.tagName,cls:e.className,width:e.getBoundingClientRect().width})));return document.documentElement.scrollWidth<=window.innerWidth;}),`Overflow at ${width}`);await page.screenshot({path:`tests/artifacts/home-${width}.png`,fullPage:true});await page.goto(origin+'/marketplace');await page.locator('[data-product-id]').first().waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),`Marketplace overflow at ${width}`);if(width===375)await page.screenshot({path:'tests/artifacts/marketplace-mobile.png',fullPage:true});}
  await page.goto(origin+'/manager');await page.screenshot({path:'tests/artifacts/manager-desktop.png',fullPage:true});await role('admin');await page.goto(origin+'/admin');page.on('dialog',dialog=>void dialog.accept());const count=await Product.countDocuments();await page.getByRole('button',{name:'Revoke access',exact:true}).first().click();await page.getByRole('button',{name:'Restore Access',exact:true}).first().waitFor();assert.equal(await Product.countDocuments(),count);await page.getByRole('button',{name:'Restore Access',exact:true}).first().click();await page.getByRole('button',{name:'Restore Access',exact:true}).waitFor({state:'hidden'});assert.equal(await Product.countDocuments(),count);assert.deepEqual(errors,[]);
  console.log('Browser passed with a real isolated database: six translated locales; voice/text actions; native replies; multi-turn capture; confirmations; microphone denial; memory removal; account edits; keyboard dialog; mobile layouts.');
}catch(error){await page.screenshot({path:'tests/artifacts/browser-failure.png',fullPage:true});console.error('Browser failure at',page.url(),errors);throw error;}finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));await mongoose.disconnect();await mongo.stop();}
