import { useEffect, useState } from 'react';
import { UserCircle, ShieldCheck, Save } from 'lucide-react';
import { useAuthStore } from '../store/useAuthStore';
import { useT } from '../components/Translate';
export default function Account(){
  const {token,setAuth}=useAuthStore(),t=useT();
  const [profile,setProfile]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(false);
  async function load(){try{const res=await fetch('/api/auth/me',{headers:{Authorization:`Bearer ${token}`}});if(!res.ok)throw new Error();const data=await res.json();setProfile(data.user);setAuth(token!,data.user);}catch{setError('Could not load account. Please try again.');}}
  useEffect(()=>{void load();window.addEventListener('account-updated',load);return()=>window.removeEventListener('account-updated',load);},[token]);
  async function save(){setBusy(true);setError('');try{const res=await fetch('/api/auth/me',{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({name:profile.name,address:profile.address || ''})});if(!res.ok)throw new Error();const data=await res.json();setAuth(token!,data.user);setProfile(data.user);setMessage('Account updated.');setReview(false);}catch{setError('Could not update account. Please try again.');}finally{setBusy(false);}}
  return <section className="max-w-2xl mx-auto py-10"><p className="section-kicker">{t('Account')}</p><h1 className="page-title mb-7">{t('Account details')}</h1>{error&&<div role="alert" className="error-banner mb-5">{t(error)}<button className="button-secondary ml-3" onClick={()=>void load()}>{t('Try again')}</button></div>}{message&&<p role="status" className="text-[#83D9BD] mb-4">{t(message)}</p>}{profile?<form className="surface-panel p-7 space-y-6" onSubmit={e=>{e.preventDefault();setReview(true);}}><div className="flex items-center gap-4"><UserCircle size={42} className="text-[#E6B879]"/><div><h2>{profile.name}</h2><p className="page-subtitle">{t(profile.role==='manager'?'Store Manager':profile.role==='admin'?'Admin':'Customer')}</p></div></div><label className="block space-y-2"><span>{t('Full Name')}</span><input className="w-full p-3 rounded-xl bg-[#0D1825] border border-[#2B4054]" required maxLength={150} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label className="block space-y-2"><span>{t('Address')}</span><textarea className="w-full p-3 rounded-xl bg-[#0D1825] border border-[#2B4054]" maxLength={1000} value={profile.address||''} onChange={e=>setProfile({...profile,address:e.target.value})}/></label><div className="flex gap-2 page-subtitle"><ShieldCheck size={17}/>{t('Changes require confirmation.')}</div>{review?<div className="flex gap-3"><button type="button" className="button-primary" disabled={busy} onClick={()=>void save()}>{t('Confirm')}</button><button type="button" className="button-secondary" onClick={()=>setReview(false)}>{t('Cancel')}</button></div>:<button className="button-primary"><Save size={17}/>{t('Save Changes')}</button>}</form>:!error&&<div className="card-skeleton"/>}</section>;
}
