import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, ShoppingBag, Wheat, Shirt, Hammer, Cpu, Mic, Sparkles, ShieldCheck, Heart, Store } from 'lucide-react';
import { motion, useReducedMotion } from 'motion/react';
import { useT } from '../components/Translate';
const categories=[['Groceries',Wheat],['Handicrafts',Hammer],['Clothing',Shirt],['Electronics',Cpu]] as const;
export default function Landing(){
  const t=useT(), reduced=useReducedMotion();
  return <div className="flex flex-col gap-16 py-8">
    <section className="hero-layout"><div><p className="section-kicker"><Sparkles size={14}/>{t('Empowering Local Micro-Commerce')}</p><h1 className="hero-heading">{t('Local finds.')}<br/><span>{t('Closer connections.')}</span></h1><p className="hero-copy">{t('We bridge the gap between skilled rural artisans, local vendors, and passionate buyers. Experience authentic craftsmanship, fresh regional produce, and personalized commerce.')}</p><div className="flex flex-wrap gap-3 mt-8"><Link to="/marketplace" className="button-primary">{t('Explore Marketplace')}<ArrowRight size={18}/></Link><Link to="/register?role=manager" className="button-secondary">{t('Join as Merchant')}<Store size={17}/></Link></div><div className="hero-trust"><ShieldCheck size={18}/><span>{t('Artisan Security')}</span><span className="text-[#E6B879]">•</span><Heart size={17}/><span>{t('Express Interest')}</span></div></div>
    <motion.div className="hero-visual" initial={reduced?false:{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:0.65}}><div className="hero-grid">{categories.map(([name,Icon],i)=><Link className={`hero-tile tile-${i}`} key={name} to={`/marketplace?category=${name}`}><Icon size={62} strokeWidth={1.3}/><span>{t(name)}</span><ArrowUpRight size={18}/></Link>)}</div><div className="hero-floating"><span className="brand-mark"><ShoppingBag size={20}/></span><div><strong>{t('Inside Tiorkhali Mart')}</strong><p>{t('Connecting Hearts, Elevating Local Crafts.')}</p></div></div></motion.div></section>
    <section><div className="flex flex-wrap items-end justify-between gap-4 mb-6"><div><p className="section-kicker">{t('Marketplace')}</p><h2 className="page-title">{t('Browse & Selection')}</h2></div><Link className="nav-link" to="/marketplace">{t('Explore Marketplace')}<ArrowUpRight size={17}/></Link></div><div className="category-row">{[['Groceries',Wheat],['Handicrafts',Hammer],['Clothing',Shirt],['Electronics',Cpu],['Hardware',Store]].map(([name,Icon]:any)=><Link className="category-link" key={name} to={`/marketplace?category=${name}`}><Icon size={24}/><span>{t(name)}</span><ArrowUpRight size={16}/></Link>)}</div></section>
    <section><div className="mb-6"><p className="section-kicker">{t('How It Works')}</p><h2 className="page-title">{t('Inside Tiorkhali Mart')}</h2></div><div className="grid md:grid-cols-3 gap-5">{[
      ['Browse & Selection','Explore authentic local merchandise listed directly by regional Store Managers, ranging from handicrafts, traditional garments, to daily groceries.',ShoppingBag],
      ['Express Interest',"button. This immediately logs an inquiry directly into the Store Manager's dashboard.",Heart],
      ['Coordinated Checkout','The Store Manager reviews your buying requests in real-time, contacts you via phone/WhatsApp, and arranges convenient delivery or pickup options.',Store]
    ].map(([title,copy,Icon]:any,i)=><article className="feature-tile" key={title}><div className="flex justify-between items-center"><Icon size={25}/><span className="text-[#7B95AD]">0{i+1}</span></div><h3>{t(title)}</h3><p>{i===1 && <>{t('I Want to Buy This')} — </>}{t(copy)}</p></article>)}</div></section>
    <section className="voice-feature"><div className="voice-orb"><Mic size={35}/></div><div className="flex-1"><p className="section-kicker">{t('Voice Assistant')}</p><h2 className="page-title">{t('Your language. Your marketplace.')}</h2><p className="page-subtitle">{t('Ask me to search products, open your dashboard or requests, or add a product.')}</p></div><button className="button-primary" onClick={()=>window.dispatchEvent(new Event('agent-open'))}>{t('Voice Assistant')}<ArrowRight size={18}/></button></section>
  </div>;
}
